### ISSUE TITLE
badges and or watermark

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog-archived-repos/meta#2]
a `conventional-changelog` badge would be cool, something similar to `standard`:

[![js-standard-style](https://img.shields.io/badge/code%20style-standard-brightgreen.svg)](http://standardjs.com/)

**Comment by bcoe** [comment]
Perhaps rather than a badge, we place a default header in changelogs generated with the tool. Something like:

``` md
[Conventional Changelog](http://conventional-changelog.github.io)

## v4.0.0
```

We would of course allow this to be overridden.

**Comment by nexdrew** [comment]
I like the watermark idea because it can be built into the generated output automatically. (But, yes, we should allow it to be disabled.)

We can easily promote a custom badge; that just means authors will have to manually paste it into their README. But it certainly wouldn't hurt!

[![Conventional Changelog](https://img.shields.io/badge/changelog-conventional-brightgreen.svg)](http://conventional-changelog.github.io)

Perhaps the badge would be better suited for the opinionated `standard-changelog` tool? I would just want it to signify that my projects (1) use structured commit messages and (2) conform to some semi-automated release process.

**Comment by stevemao** [comment]
Great idea!!

> Perhaps the badge would be better suited for the opinionated standard-changelog tool?

Agree. Really like how the badge looks :)

If a user is using, say jshint convention, is it possible to say "changelog" "conventional" "jshint" on the badge? It's a bit long but fine.

**Comment by bcoe** [comment]
I have added @nexdrew's badge to `standard-version`.

**Comment by stevemao** [comment]
I want to reopen this coz I haven't added any badges to other other modules.
